name: Automated MLOps Testing

on:
  push:
    branches:
      - dev

jobs:
  check_working_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Repository Code
      uses: actions/checkout@v4

    - name: Initialize Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Required Libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train.py

    - name: Run testing script
      run: |
        python test.py